"""Agent result schemas."""

from __future__ import annotations

from pydantic import BaseModel, Field, field_validator


class Observation(BaseModel):
    """Result of executing a single action in the ReAct loop."""

    content: str
    tool_name: str | None = None
    tool_args: dict | None = None
    latency_ms: float = 0.0


class Step(BaseModel):
    """Single step in the ReAct execution loop."""

    thought: str
    action: str
    observation: Observation | None = None


class Plan(BaseModel):
    """High-level execution plan generated by the Planner."""

    query: str
    steps: list[Step]
    estimated_complexity: str = "medium"  # "low" | "medium" | "high"

    @field_validator("estimated_complexity")
    @classmethod
    def validate_complexity(cls, v: str) -> str:
        if v not in {"low", "medium", "high"}:
            raise ValueError("estimated_complexity must be low, medium, or high")
        return v


class AgentResult(BaseModel):
    """Final output of the Agent."""

    plan: Plan
    answer: str
    sources: list = Field(default_factory=list)
    metadata: dict = Field(default_factory=dict)
